CREATE TABLESPACE  MALL_ADMIN
DATAFILE '/u01/app/oracle/oradata/orcl/mall_admin.dbf' 
SIZE 200M 
AUTOEXTEND ON 
NEXT 200M MAXSIZE UNLIMITED 
EXTENT MANAGEMENT LOCAL;  


CREATE TEMPORARY TABLESPACE MALL_ADMIN_TEMP  
TEMPFILE '/u01/app/oracle/oradata/orcl/mall_admin_temp.dbf'  
SIZE 200M  
AUTOEXTEND ON  
NEXT 50M MAXSIZE UNLIMITED  
EXTENT MANAGEMENT LOCAL;  


CREATE USER MALL_ADMIN IDENTIFIED BY "MALL_ADMIN" DEFAULT TABLESPACE MALL_ADMIN TEMPORARY TABLESPACE MALL_ADMIN_TEMP;  



GRANT CREATE USER,DROP USER,ALTER USER ,CREATE ANY VIEW ,  
     DROP ANY VIEW,EXP_FULL_DATABASE,IMP_FULL_DATABASE,  
     DBA,CONNECT,RESOURCE,CREATE SESSION TO  MALL_ADMIN;  



