server:
  port: 8081  #dockfile ENV 设置覆盖 当前开发使用
#  ssl:
#    key-store: classpath:auth.keystore
#    key-store-password: 123456
#    key-password: 123456
  tomcat:
      max-threads:  200
      uri-encoding: UTF-8

#mybatis config
mybatis:
  mapper-locations: classpath*:mapper/mysql/*.xml
  type-aliases-package: com.xwtech.framework.shiro.model.auth

#spring.datasource
spring:
  application:
    name: xwtec-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/voplatform?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vo
    password: voxwtec
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
#SELECT 1 FROM DUAL
      connection-test-query: SELECT 1
      idle-timeout: 10000
      validation-timeout: 10000
 #REDIS (RedisProperties)
  redis:
    database: 0
    host: 10.19.241.52
    port: 6381
    pool:
      max-active: 200
      max-wait: 5000
      max-idle: 20
      min-idle: 1
  cache:
    type: redis
    cache-names:
      - 'center::auth'
  aop:
    proxy-target-class: true

#shiro权限
shiro:
  session:
    name: sid
    domain:
    path: /
    httpOnly: true
    MaxAge: -1
  rememberMe:
    name: rememberMe
    domain:
    path: /
    httpOnly: true
    MaxAge: -1
  server:
    hashIterations: 2
    hashAlgorithmName: md5
    globalSessionTimeout: 1800000 #默认30分钟
  client:
    appKey: xwtec-admin
    platformKey: default-xwtec-monitor
    globalAuthUrl: http://10.19.245.186:8881/center
    loginUrl: http://10.19.245.186:8881/center/login
    successUrl: http://10.19.245.186:8881/web/index
    unauthorizedUrl: /unauthorized
    definitions:
      /static/**: anon
      /: authc
      /index: authc
      /user/**: authc
      /resource/**: authc
      /role/**: authc

web:
  staticUrl: http://10.19.245.186:8881/center

log:
  path: logs/
  level: info
  appender: rollingFile
#---
## 测试环境配置
#spring:
#  profiles: test
#
#
#---
## 生产环境配置
#spring:
#  profiles: prod










